language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install seaborn
  - pip install pandas
  - pip install feather
  - pip install halo